const players = [
    { no: 1, name: "Beau Alvarez", pos: "C", year: "Junior", ht: "6'1\"", wt: "210 lbs", hometown: "Redondo Beach, CA", school: "Redondo Union HS", bt: "R/R", image: "images/1 Beau Alvarez.jpg",
        major: "Architecture",
        food: "Fish tacos",
        interests: "Surfing, The Last Dance (TV), Inception (movie), The Weeknd (music)",
        funfact: "Makes $5,000 a month on Cameo",},
    { no: 2, name: "Kyson Frost", pos: "OF", year: "Junior", ht: "6'0\"", wt: "185 lbs", hometown: "Atlanta, GA", school: "Marist HS", bt: "R/R", image: "images/2 Kyson Frost.jpg",
        major: "Painting",
        food: "Breakfast",
        interests: "Crossword puzzles, Parks & Rec (TV), Interstellar (movie), Dune (book)",
        funfact: "Spent a night in the American Museum of Natural History, like in that movie",},
    { no: 3, name: "Garret Smink", pos: "UT", year: "Junior", ht: "6'2\"", wt: "210 lbs", hometown: "Newton, MA", school: "Newton North HS", bt: "R/R", image: "images/3 Garret Smink.jpg",
        major: "Illustration",
        food: "Homemade pasta",
        interests: "Cooking, karaoke, The Grand Budapest Hotel (movie), 80s music",
        funfact: "Tries every year to organize a flash mob with teammates (so far unsuccessful)",},
    { no: 4, name: "Bryce Ready", pos: "INF", year: "Freshman", ht: "6'1\"", wt: "220 lbs", hometown: "Murrysville, PA", school: "Franklin Regional HS", bt: "R/R", image: "images/4 Bryce Ready.jpg",
        major: "Graphic design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Can mimic 34 different bird calls",},
    { no: 5, name: "KJ DeBarge", pos: "INF", year: "Junior", ht: "6'3\"", wt: "190 lbs", hometown: "Potomac, MD", school: "Bullis HS", bt: "R/R", image: "images/5 KJ DeBarge.jpg",
        major: "Architecture",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Is followed by Alex Rodriguez on Instagram",},
    { no: 6, name: "Tanner Swain", pos: "INF", year: "Sophomore", ht: "6'5\"", wt: "240 lbs", hometown: "Syracuse, NY", school: "Cicero-North Syracuse HS", bt: "R/R", image: "images/6 Tanner Swain.jpg",
        major: "Printmaking",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Once got lost in the woods for three days",},
    { no: 7, name: "Trey Favors", pos: "INF", year: "Freshman", ht: "5'10\"", wt: "175 lbs", hometown: "San Diego, CA", school: "St. Augustine HS", bt: "L/R", image: "images/7 Trey Favors.jpg",
        major: "Animation",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Experienced ego death in 2022",},
    { no: 8, name: "Tatsunori Schmidt", pos: "UT", year: "Freshman", ht: "6'1\"", wt: "200 lbs", hometown: "Lexington, MA", school: "Minuteman Regional HS", bt: "L/L", image: "images/8 Tatsunori Schmidt.jpg",
        major: "Interior design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Spent a week living at LaGuardia while waiting for his lease to start",},
    { no: 9, name: "Walker Mendez", pos: "INF", year: "Sophomore", ht: "6'1\"", wt: "205 lbs", hometown: "Wayne, NJ", school: "Wayne Hills HS", bt: "L/R", image: "images/9 Walker Mendez.jpg",
        major: "Architecture",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Hit a walk-off grand slam in high school",},
    { no: 10, name: "Clyde Babee", pos: "RHP", year: "Freshman", ht: "6'2\"", wt: "0 lbs", hometown: "Houston, TX", school: "Cy Ranch HS", bt: "R/R", image: "images/10 Clyde Babee.jpg",
        major: "Drawing",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Still trying to make money on Gamestop shares he bought in 2021",},
    { no: 11, name: "Khal Valdez", pos: "RHP", year: "Sophomore", ht: "6'0\"", wt: "180 lbs", hometown: "Naples, FL", school: "Gulf Coast HS", bt: "R/R", image: "images/11 Khal Valdez.jpg",
        major: "Industrial design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Hates revolving doors",},
    { no: 12, name: "Tressa Scar", pos: "OF", year: "Freshman", ht: "5'10\"", wt: "0 lbs", hometown: "San Marcos, CA", school: "San Marcos HS", bt: "R/R", image: "images/12 Tressa Scar.jpg",
        major: "Graphic design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Has a black belt in karate",},
    { no: 13, name: "Reese Witherspoon", pos: "RHP", year: "Sophomore", ht: "6'2\"", wt: "195 lbs", hometown: "San Antonio, TX", school: "Warren HS", bt: "R/R", image: "images/13 Reese Witherspoon.jpg",
        major: "Illustration",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Won an academy award for Walk the Line",},
    { no: 14, name: "RJ Zimbardo", pos: "C", year: "Freshman", ht: "5'10\"", wt: "180 lbs", hometown: "Fresno, CA", school: "Fresno HS", bt: "R/R", image: "images/14 RJ Zimbardo.jpg",
        major: "Industrial design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Is related to Philip Zimbardo, the psychologist behind the Stanford Prison Experiment",},
    { no: 15, name: "Dalton Seeker", pos: "OF", year: "Junior", ht: "6'2\"", wt: "190 lbs", hometown: "Mooresville, IN", school: "Mooresville HS", bt: "L/L", image: "images/15 Dalton Seeker.jpg",
        major: "Animation",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Owns a really expensive telescope",},
    { no: 16, name: "Dean Devine", pos: "LHP", year: "Junior", ht: "5'11\"", wt: "200 lbs", hometown: "Fort Smith, AR", school: "Northside HS", bt: "L/L", image: "images/16 Dean Devine.jpg",
        major: "Graphic design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Recreationally distills moonshine in a bathtub with his uncle",},
    { no: 17, name: "Griffin Kuntz", pos: "LHP", year: "Senior", ht: "6'1\"", wt: "190 lbs", hometown: "San Jose, CA", school: "Pioneer HS", bt: "L/L", image: "images/17 Griffin Kuntz.jpg",
        major: "Film",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Brews his own kombucha",},
    { no: 18, name: "Clayton Krauss", pos: "RHP", year: "Senior", ht: "6'5\"", wt: "225 lbs", hometown: "Fairfield, CT", school: "Fairfield Warde HS", bt: "R/R", image: "images/18 Clayton Krauss.jpg",
        major: "Drawing",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Once caught a fish out of the ocean with his bare hand",},
    { no: 19, name: "Blake Blanco", pos: "OF", year: "Sophomore", ht: "6'2\"", wt: "210 lbs", hometown: "Phoenix, AZ", school: "O'Connor HS", bt: "R/R", image: "images/19 Blake Blanco.jpg",
        major: "Illustration",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Is thinking about becoming a Disney adult",},
    { no: 20, name: "Yorks Font", pos: "OF", year: "Junior", ht: "6'0\"", wt: "0 lbs", hometown: "Corona, CA", school: "Corona HS", bt: "R/R", image: "images/20 Yorks Font.jpg",
        major: "Architecture",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Commutes around the city on a bike that he stole from an SVA student",},
    { no: 21, name: "Carter Sass", pos: "OF", year: "Freshman", ht: "5'10\"", wt: "180 lbs", hometown: "Suwanee, GA", school: "North Gwinnett HS", bt: "R/R", image: "images/21 Carter Sass.jpg",
        major: "Interior design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Once guessed the Wordle on his first try",},
    { no: 22, name: "Michael Vu", pos: "RHP", year: "Sophomore", ht: "6'2\"", wt: "180 lbs", hometown: "Las Vegas, NV", school: "Palo Verde HS", bt: "R/R", image: "images/22 Michael Vu.jpg",
        major: "Graphic design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Can eat 50 hot wings in 6 minutes",},
    { no: 23, name: "Tyler Quinlan", pos: "OF", year: "Junior", ht: "6'1\"", wt: "215 lbs", hometown: "Keller, TX", school: "Keller HS", bt: "L/L", image: "images/23 Tyler Quinlan.jpg",
        major: "Painting",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Built a working model train set",},
    { no: 24, name: "Jordan Mallory Jr.", pos: "OF", year: "Sophomore", ht: "6'2\"", wt: "200 lbs", hometown: "Bellaire, TX", school: "Episcopal HS", bt: "L/R", image: "images/24 Jordan Mallory Jr.jpg",
        major: "Animation",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Has a pet ferret named Ferret Bueller",},
    { no: 25, name: "Aaron Toole", pos: "RHP", year: "Freshman", ht: "5'11\"", wt: "170 lbs", hometown: "New York, NY", school: "Poly Prep HS", bt: "R/R", image: "images/25 Aaron Toole.jpg",
        major: "Graphic design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Can solve a Rubik's cube in 40 seconds",},
    { no: 26, name: "Kellen Mercer", pos: "RHP", year: "Senior", ht: "6'2\"", wt: "205 lbs", hometown: "Narragansett, RI", school: "Narragansett HS", bt: "R/R", image: "images/26 Kellan Mercer.jpg",
        major: "Architecture",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Once had to go to the ER after being bitten by a raccoon",},
    { no: 27, name: "Nick Driscoll", pos: "RHP", year: "Freshman", ht: "5'11\"", wt: "175 lbs", hometown: "Oakwood, OH", school: "Oakwood HS", bt: "R/R", image: "images/27 Nick Driscoll.jpg",
        major: "Film",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Is really good at card tricks",},
    { no: 28, name: "Kenneth Couture", pos: "LHP", year: "Freshman", ht: "6'6\"", wt: "185 lbs", hometown: "Brooklyn, NY", school: "Jefferson HS", bt: "L/L", image: "images/28 Kenneth Couture.jpg",
        major: "Fashion design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Was an extra in an episode of Law & Order SVU",},
    { no: 29, name: "Niko Serrano", pos: "INF", year: "Junior", ht: "6'0\"", wt: "185 lbs", hometown: "Winston-Salem, NC", school: "Oak Grove HS", bt: "L/R", image: "images/29 Niko Serrano.jpg",
        major: "Industrial design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Has crashed a couple weddings",},
    { no: 30, name: "Kermit Grastan", pos: "UT", year: "Junior", ht: "6'2\"", wt: "0 lbs", hometown: "Brookline, MA", school: "Brookline HS", bt: "R/R", image: "images/30 Kermit Grastan.jpg",
        major: "Illustration",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Has a collection of old security footage that he watches in his free time",},
    { no: 31, name: "Chris McCrystal", pos: "LHP", year: "Senior", ht: "6'3\"", wt: "215 lbs", hometown: "Golden, CO", school: "Golden HS", bt: "L/L", image: "images/31 Chris McCrystal.jpg",
        major: "Photography",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Is certified in falconry",},
    { no: 32, name: "Jurrangelo Kryszczuk", pos: "RHP", year: "Junior", ht: "6'5\"", wt: "220 lbs", hometown: "Gurnee, IL", school: "Warren Township HS", bt: "R/R", image: "images/32 Jurrangelo Kryszczuk.jpg",
        major: "Fine arts",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Once caught a home run ball from a ferris wheel at a minor league game",},
    { no: 33, name: "Mitch Grinsell", pos: "C", year: "Senior", ht: "6'1\"", wt: "205 lbs", hometown: "Sugar Land, TX", school: "Fort Bend Clements HS", bt: "R/R", image: "images/33 Mitch Grinsell.jpg",
        major: "Architecture",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Has never lost a coin flip and never will",},
    { no: 34, name: "Matt Pennington", pos: "INF", year: "Junior", ht: "6'4\"", wt: "210 lbs", hometown: "Rockaway, NJ", school: "Morris Knolls HS", bt: "R/R", image: "images/34 Matt Pennington.jpg",
        major: "Industrial design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Dream job growing up was Abercrombie store model",},
    { no: 35, name: "Linzora Shatzman", pos: "LHP", year: "Sophomore", ht: "5'8\"", wt: "0 lbs", hometown: "Mason, OH", school: "Ursuline Academy", bt: "L/L", image: "images/35 Linzora Shatzman.jpg",
        major: "Fine arts",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Won a watermelon seed-spitting contest at age 7",},
    { no: 36, name: "Dom Compton", pos: "RHP", year: "Junior", ht: "6'2\"", wt: "195 lbs", hometown: "Boca Raton, FL", school: "Boca Raton HS", bt: "R/R", image: "images/36 Dom Compton.jpg",
        major: "Graphic design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Secretly has nine cats in his dorm room",},
    { no: 37, name: "Melvin Carroule", pos: "C", year: "Junior", ht: "6'1\"", wt: "0 lbs", hometown: "Scottsdale, AZ", school: "Saguaro HS", bt: "R/R", image: "images/37 Melvin Carroule.jpg",
        major: "Interior design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Runs a popular YouTube account where he posts video essays about cryptids",},
    { no: 38, name: "Luke Pooser", pos: "LHP", year: "Sophomore", ht: "6'4\"", wt: "215 lbs", hometown: "Staten Island, NY", school: "Tottenville HS", bt: "L/L", image: "images/38 Luke Pooser.jpg",
        major: "Undeclared",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Kicked out of his first middle school for starting a fight club",},
    { no: 39, name: "Travis Desandro", pos: "1B", year: "Sophomore", ht: "5'11\"", wt: "190 lbs", hometown: "Oakland, CA", school: "Fremont HS", bt: "L/L", image: "images/39 Travis Desandro.jpg",
        major: "Photography",
        food: "Lucky Charms",
        interests: "-undefined-",
        funfact: "Favorite cereal is Lucky Charms",},
    { no: 40, name: "Leighton D'Amato", pos: "INF", year: "Senior", ht: "6'0\"", wt: "210 lbs", hometown: "Austin, TX", school: "Lake Travis HS", bt: "L/L", image: "images/40 Leighton D'Amato.jpg",
        major: "Art education",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Won't tell anyone his real age",},
    { no: 41, name: "Maina Dogsta", pos: "1B", year: "Senior", ht: "5'10\"", wt: "0 lbs", hometown: "Langley, BC", school: "Brookswood Secondary", bt: "L/L", image: "images/41 Maina Dogsta.jpg",
        major: "Creative writing",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Wants to try cyberbullying but knows it's wrong",},
    { no: 43, name: "Brent Tracer", pos: "RHP", year: "Senior", ht: "6'4\"", wt: "0 lbs", hometown: "Sydney, Australia", school: "Turramurra HS", bt: "R/R", image: "images/43 Brent Tracer.jpg",
        major: "Animation",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Started a small microwave fire on the Steuben fourth floor",},
    { no: 44, name: "Donnisa Chilsick", pos: "LHP", year: "Junior", ht: "5'9\"", wt: "0 lbs", hometown: "Marietta, GA", school: "Walton HS", bt: "L/L", image: "images/44 Donnisa Chilsick.jpg",
        major: "Industrial design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Has an identical twin with whom she can communicate telepathically",},
    { no: 45, name: "Elmo Stich", pos: "INF", year: "Sophomore", ht: "6'0\"", wt: "0 lbs", hometown: "Waianae, HI", school: "Maryknoll HS", bt: "R/R", image: "images/45 Elmo Stich.jpg",
        major: "Interior design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Keeps having encounters with ghosts but no one believes him",},
    { no: 47, name: "Reed Clonne", pos: "OF", year: "Sophomore", ht: "5'9\"", wt: "0 lbs", hometown: "Providence, KY", school: "Webster County HS", bt: "L/R", image: "images/47 Reed Clonne.jpg",
        major: "Painting",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Banned from every Applebee's location",},
    { no: 48, name: "Mony Coblas", pos: "RHP", year: "Junior", ht: "5'8\"", wt: "0 lbs", hometown: "Detroit, MI", school: "Central HS", bt: "R/R", image: "images/48 Mony Coblas.jpg",
        major: "Architecture",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Still uses BeReal",},
    { no: 49, name: "Whres Eet", pos: "INF", year: "Junior", ht: "5'10\"", wt: "0 lbs", hometown: "Corpus Christi, TX", school: "Mary Carroll HS", bt: "L/R", image: "images/49 Whres Eet.jpg",
        major: "Game design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Throws right-handed but writes left-handed",},
    { no: 51, name: "Lanny Mandon", pos: "C", year: "Senior", ht: "5'9\"", wt: "0 lbs", hometown: "Los Angeles, CA", school: "Notre Dame HS", bt: "R/R", image: "images/51 Lanny Mandon.jpg",
        major: "Interior design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Snuck into the People's Choice Awards by being hot",},
    { no: 52, name: "Leona Rotor", pos: "RHP", year: "Freshman", ht: "5'11\"", wt: "0 lbs", hometown: "Memphis, TN", school: "Collierville HS", bt: "R/R", image: "images/52 Leona Rotor.jpg",
        major: "Fashion design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Is a skilled self-taught accordion player",},
    { no: 53, name: "Laren Pyton", pos: "UT", year: "Sophomore", ht: "5'8\"", wt: "0 lbs", hometown: "Rose Bud, AR", school: "Rose Bud HS", bt: "L/L", image: "images/53 Laren Pyton.jpg",
        major: "Fine arts",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Collects vintage typewriters",},
    { no: 54, name: "Cassio Farrane", pos: "RHP", year: "Junior", ht: "6'3\"", wt: "0 lbs", hometown: "Hartsville, SC", school: "Hartsville HS", bt: "R/R", image: "images/54 Cassio Farrane.jpg",
        major: "Graphic design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Trained a local crow to bring leave shiny objects on his windowsill",},
    { no: 55, name: "Nilo Socc", pos: "INF", year: "Senior", ht: "5'11\"", wt: "0 lbs", hometown: "Ballston Spa, NY", school: "Ballston Spa HS", bt: "R/R", image: "images/55 Nilo Socc.jpg",
        major: "Architecture",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Loves Snoopy",},
    { no: 57, name: "Mavis Shen", pos: "OF", year: "Senior", ht: "5'9\"", wt: "0 lbs", hometown: "Aurora, IL", school: "Oswego East HS", bt: "L/L", image: "images/57 Mavis Shen.jpg",
        major: "Graphic design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Is an amateur storm chaser",},
    { no: 60, name: "Warren Saint", pos: "INF", year: "Sophomore", ht: "6'5\"", wt: "0 lbs", hometown: "Oshkosh, WI", school: "Oshkosh North HS", bt: "R/R", image: "images/60 Warren Saint.jpg",
        major: "Industrial design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Completed a marathon despite not having trained for it",},
    { no: 62, name: "Reneck Mellet", pos: "RHP", year: "Senior", ht: "6'2\"", wt: "0 lbs", hometown: "Abbeville, LA", school: "Vermilion Catholic HS", bt: "R/R", image: "images/62 Reneck Mellet.jpg",
        major: "Industrial design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Once hiked 50 miles through the Bayou without a map, relying solely on instinct",},
    { no: 63, name: "Ebolda Huntin", pos: "INF", year: "Freshman", ht: "5'9\"", wt: "0 lbs", hometown: "Port St. Lucie, FL", school: "Treasure Coast HS", bt: "R/R", image: "images/63 Ebolda Huntin.jpg",
        major: "Architecture",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Can speak three different languages",},
    { no: 66, name: "Dante Info", pos: "C", year: "Freshman", ht: "6'3\"", wt: "0 lbs", hometown: "West Palm Beach, FL", school: "Palm Beach Gardens HS", bt: "R/R", image: "images/66 Dante Info.jpg",
        major: "Sculpture",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Is the drummer for Future Less Vivid, a band he started with his friends",},
    { no: 67, name: "Wren Pagon", pos: "INF", year: "Junior", ht: "5'9\"", wt: "0 lbs", hometown: "Cerritos, CA", school: "Gahr HS", bt: "L/R", image: "images/67 Wren Pagon.jpg",
        major: "Industrial design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Was on an episode of Shark Tank",},
    { no: 69, name: "Cumnong Hamdic", pos: "INF", year: "Freshman", ht: "6'2\"", wt: "0 lbs", hometown: "Niceville, FL", school: "Niceville HS", bt: "L/L", image: "images/69 Cumnong Hamdic.jpg",
        major: "Sculpture",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Does the cinnamon challenge and is good at it",},
    { no: 71, name: "Luffin Grikintz", pos: "LHP", year: "Senior", ht: "6'1\"", wt: "0 lbs", hometown: "San Jose, CA", school: "Leland HS", bt: "L/L", image: "images/71 Luffin Grikintz.jpg",
        major: "Art history",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Is Griffin Kuntz' Wario",},
    { no: 75, name: "Lexy Adnhea", pos: "OF", year: "Sophomore", ht: "5'10\"", wt: "0 lbs", hometown: "San Antonio, TX", school: "Sandra Day O'Connor HS", bt: "R/R", image: "images/75 Lexy Adnhea.jpg",
        major: "Photography",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Wears mismatched socks during every game for good luck",},
    { no: 77, name: "Coin Klank", pos: "LHP", year: "Junior", ht: "6'2\"", wt: "0 lbs", hometown: "Reno, NV", school: "Reno HS", bt: "L/L", image: "images/77 Coin Klank.jpg",
        major: "Graphic design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Legally changed his first name to Coin after becoming a crypto millionaire",},
    { no: 78, name: "Jolka Bot", pos: "RHP", year: "Sophomore", ht: "5'8\"", wt: "0 lbs", hometown: "Seoul, South Korea", school: "Kyunggi HS", bt: "R/R", image: "images/78 Jolka Bot.jpg",
        major: "Illustration",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Wears sunglasses in every postgame interview",},
    { no: 82, name: "Tucketh Norene", pos: "LHP", year: "Freshman", ht: "5'10\"", wt: "0 lbs", hometown: "Carmel, IN", school: "University HS", bt: "L/L", image: "images/82 Tucketh Norene.jpg",
        major: "Creative writing",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Won a statewide poetry slam in high school",},
    { no: 84, name: "Blon Narkel", pos: "RHP", year: "Junior", ht: "5'11\"", wt: "0 lbs", hometown: "Hayward, CA", school: "Moreau Catholic HS", bt: "R/R", image: "images/84 Blon Narkel.jpg",
        major: "Fashion design",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Had a Twitter feud with the host of Call Her Daddy",},
    { no: 88, name: "Nutpuck Minimick", pos: "RHP", year: "Sophomore", ht: "6'4\"", wt: "0 lbs", hometown: "Halifax, Nova Scotia", school: "Foothills Composite HS", bt: "R/R", image: "images/88 Nutpuck Minimick.jpg",
        major: "Cultural studies",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Has had COVID six times",},
    { no: 92, name: "Rokie Sarnon", pos: "INF", year: "Junior", ht: "5'9\"", wt: "0 lbs", hometown: "Mission Viejo, CA", school: "Capistrano Valley HS", bt: "L/R", image: "images/92 Rokie Sarnon.jpg",
        major: "Architecture",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Can burp the alphabet",},
    { no: 99, name: "Yonk Ribell", pos: "OF", year: "Freshman", ht: "5'11\"", wt: "0 lbs", hometown: "Albuquerque, NM", school: "Sandia HS", bt: "L/R", image: "images/99 Yonk Ribell.jpg",
        major: "Film",
        food: "-undefined-",
        interests: "-undefined-",
        funfact: "Was once interviewed on local TV for rescuing a turtle from a drainage pipe",},
];
